services:
  db:
    image: 'postgres:16.1'
    container_name: 'antiqbrasbloq_db_container'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    restart: always